# These are supported funding model platforms

github: [adeeteya]
patreon: adeeteya
ko_fi: adeeteya
liberapay: adeeteya
custom: ['https://www.buymeacoffee.com/adeeteya','https://www.paypal.me/adityar224']
